version: "3"

services:
  rabbitmq:
   container_name: rabbitmq
   image: rabbitmq:3-management
   environment:
     RABBITMQ_ERLANG_COOKIE: SuperSecret
     #RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
     #RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
   ports:
   - 5672
   - 15672:15672
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:15672"]
     interval: 30s
     timeout: 10s
     retries: 5

  collector:
    container_name: collector
    build: ./collector
    restart: on-failure
    depends_on:
    - rabbitmq

  emitter:
    container_name: emitter
    build: ./emitter
    restart: on-failure
    depends_on:
    - rabbitmq

